### ISSUE TITLE
Not generating trustedgrub_install.sh

### ISSUE THREAD

**Issue by NeryHenrique** [Aircloak/TrustedGRUB#2]
Hi Cristian,

I m trying to use your Tgrub fork in a Ubuntu 12.04 64bits.

I manage to compile with:
sudo apt-get install automake autoconf gcc-multilib libc6-i386 build-essential texinfo

now fix one missing file asked for make:
cp Original_GRUB_ChangeLog ChangeLog

and everything is fine, except that it dont generate trustedgrub_install.sh,
i searched in the folder and didnt found any mention to it too.
what should i do?

Thanks,
Henrique

**Comment by cristianberneanu** [comment]
Hi Henrique,

Thanks for the bug report.

I left the installation script (trustedgrub_install.sh) uncommitted because I wanted to test it first, but I haven't had the chance to do that until now as I was always busy with something else. I previously installed TrustedGRUB on a machine by running the commands manually, so it should work.

I have pushed a commit that fixes the build process and adds the missing script.

**Be warned that the installation script is NOT tested.**
Please execute it first on a machine on which you don't have any valuable data on.

Good luck.

**Comment by NeryHenrique** [comment]
Thanks,
i will do it manually following the script and then i give u the feedback.
BR,


Henrique de Souza Nery

Date: Thu, 19 Mar 2015 10:43:38 -0700
